# Generated by Django 3.2 on 2021-04-11 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Tytuł')),
                ('slug', models.SlugField(max_length=128, unique_for_date=True)),
                ('content', models.TextField(verbose_name='Treść')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data publikacji')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('status', models.CharField(choices=[('draft', 'roboczy'), ('published', 'opublikowany')], max_length=16)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
